import test from 'node:test';
import {communityHash} from '../worker/community.mjs';
import assert from 'node:assert/strict';
import worker from '../dist/server/index.js';
import {localDatabase} from './database.mjs';
test('Amazon landing has one purchase destination and no checkout or demo assets',async()=>{const html=await(await worker.fetch(new Request('https://book.example/'),{})).text();assert.match(html,/Donde siempre estuviste/);assert.doesNotMatch(html,/Fumada|order-dialog|cart-open|demo-session|demo-checkout|shop\.js|href="\/devoluciones"|href="\/demo"/);assert.equal([...html.matchAll(/data-track="amazon"/g)].length,2);assert.match(html,/ficha del libro/);for(const path of ['/api/admin/orders','/api/returns/case','/api/demo/session','/admin/app.js','/shop.js','/returns.js','/tienda-demo.html']){const r=await worker.fetch(new Request('https://book.example'+path),{});assert.ok([404,410].includes(r.status),path);}for(const [path,to]of [['/devoluciones','/condiciones-de-venta#amazon'],['/admin','/propietario'],['/?demo=1','/']]){const r=await worker.fetch(new Request('https://book.example'+path),{});assert.equal(r.status,301);assert.equal(r.headers.get('location'),to);}});
test('canonical HTTPS host, clean routes and correct private access',async()=>{for(const from of ['http://prueba-aleix.com/','https://www.prueba-aleix.com/','https://fumada-xxl-aleix.scroll-magenta-7y.chatgpt.site/']){const r=await worker.fetch(new Request(from),{});assert.equal(r.status,301);assert.equal(r.headers.get('location'),'https://prueba-aleix.com/');}assert.equal((await worker.fetch(new Request('https://book.example/propietario'),{})).status,302);assert.equal((await worker.fetch(new Request('https://book.example/propietario.html'),{})).status,404);for(const route of ['comunidad','privacidad','cookies','aviso-legal','condiciones-de-venta','normas-comunidad']){const r=await worker.fetch(new Request('https://book.example/'+route),{});assert.equal(r.status,200);assert.equal(r.headers.get('x-robots-tag'),null);assert.match(r.headers.get('strict-transport-security'),/max-age/);assert.equal((await worker.fetch(new Request('https://book.example/'+route+'.html'),{})).headers.get('location'),'/'+route);}});
test('all same-origin page assets and links resolve without broken pages',async()=>{for(const path of ['/','/comunidad','/privacidad','/cookies','/aviso-legal','/condiciones-de-venta','/normas-comunidad']){const html=await(await worker.fetch(new Request('https://book.example'+path),{})).text();for(const [,raw]of html.matchAll(/(?:href|src)="([^"]+)"/g)){const url=new URL(raw,'https://book.example'+path);if(url.origin!=='https://book.example'||url.pathname.startsWith('/auth/'))continue;const r=await worker.fetch(new Request(url),{});assert.ok(r.status>=200&&r.status<400,raw+' on '+path+' = '+r.status);}}});
test('analytics accepts only consented bounded events and owner-only aggregate stats',async()=>{const env={DB:localDatabase(),ADMIN_OWNER_EMAIL:'owner@example.test'},call=(body,headers={})=>worker.fetch(new Request('https://book.example/api/event',{method:'POST',headers:{Origin:'https://book.example','Content-Type':'application/json','X-Site-Event':'1','CF-Connecting-IP':'test-ip',...headers},body:JSON.stringify(body)}),env);assert.equal((await call({consent:false,event:'view',page:'home'})).status,400);assert.equal((await call({consent:true,event:'view',page:'home'},{Origin:'https://other.test'})).status,403);assert.equal((await call({consent:true,event:'view',page:'home'},{DNT:'1'})).status,403);assert.equal((await call({consent:true,event:'view',page:'home'})).status,204);assert.equal((await call({consent:true,event:'amazon',page:'home'})).status,204);assert.equal((await call({consent:true,event:'amazon',page:'email@example.test'})).status,400);assert.equal((await worker.fetch(new Request('https://book.example/api/site-metrics'),env)).status,403);env.DB.sqlite.prepare('INSERT INTO community_users(id,google_sub,email,created_at) VALUES(?,?,?,?)').run('owner','google-owner','owner@example.test',1);env.DB.sqlite.prepare('INSERT INTO community_owner VALUES(1,?)').run('owner');env.DB.sqlite.prepare('INSERT INTO community_sessions VALUES(?,?,?)').run(await communityHash('x'.repeat(43)),'owner',Date.now()+60000);const stats=await worker.fetch(new Request('https://book.example/api/site-metrics',{headers:{Cookie:'__Host-community='+'x'.repeat(43)}}),env);assert.equal(stats.status,200);const data=await stats.json();assert.equal(data.rows.length,2);assert.equal(data.rows.reduce((n,r)=>n+r.count,0),2);assert.doesNotMatch(JSON.stringify(data),/test-ip|@example/);});

test('health detects database failure without exposing internal errors',async()=>{
 const ready=await worker.fetch(new Request('https://book.example/health'),{DB:localDatabase()});assert.equal(ready.status,200);assert.deepEqual(await ready.json(),{ok:true});
 const failed=await worker.fetch(new Request('https://book.example/health'),{DB:{prepare(){throw Error('private database details');}}});assert.equal(failed.status,503);assert.match(failed.headers.get('cache-control'),/no-store/);assert.doesNotMatch(await failed.text(),/private database/);
});

test('HTML uses a fresh security nonce without accepting arbitrary inline scripts or stale validators',async()=>{
 const call=()=>worker.fetch(new Request('https://book.example/',{headers:{'If-None-Match':'*'}}),{});
 const a=await call(),b=await call();for(const r of [a,b]){assert.equal(r.status,200);assert.equal(r.headers.get('etag'),null);assert.match(r.headers.get('cache-control'),/no-store/);assert.doesNotMatch(r.headers.get('content-security-policy'),/unsafe-inline|unsafe-eval/);}
 const nonce=r=>r.headers.get('content-security-policy').match(/'nonce-([^']+)'/)[1];assert.equal(Buffer.from(nonce(a),'base64').length,18);assert.notEqual(nonce(a),nonce(b));
});
